### ISSUE TITLE
Devision by zero in sine fit

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#103]
Migration: trac#270.

Devision by zero in do fit of pulsedmeasurement_logic when there is no data and one presses fit in sine the frequency which is 0 is devided in order to calculate period.

**Comment by Neverhorst** [comment]
This has nothing to do with pulsed_measurement_logic. The Sine fit fails when only zeros are passed.

**Comment by Neverhorst** [comment]
Should be fixed with pr #330
