### ISSUE TITLE
the method set_counting_mode is not working in counter_logic

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#112]
Migration: trac#327.

It is not possible to select the counting mode in the counter_logic. Always the default counting mode 'continuous' remains.
It seems that the way the values of the constraints are checked is not correct. Please fix that.

**Comment by kay-jahnke** [comment]
Fixed the Issue by forcing the counting mode to by saved as the Custom Enum Object, defined by the slow_counter_interface.
In dummy everything works but the gated and finite_gated can't be tested with dummy. Nevertheless this issue is resolved.

**Comment by kay-jahnke** [comment]
solved in commit  95b5741
