### ISSUE TITLE
Remote module rpyc has problems after several restarts of the Qudi

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#113]
Migration: trac#328.

On Windows machines, I received after some restarts of Qudi a remote connection error.

I am connected to jupyter notebook and after several restarts (and reconnects of the Qudi kernel) I got the following traceback:

```
Remote connection not secured! Use a certificate!

Traceback (most recent call last):

    File "C:\Users\astark\Dropbox\Doctorwork\Software\QuDi?-Git\qudi\core\remote.py", line 213, in run

        protocol_config={'allow_all_attrs': True})

    File "C:\Program Files\Anaconda3\lib\site-packages\rpyc\utils\server.py", line 78, in init

        self.listener.bind((hostname, port))

OSError: 10048? Only one usage of each socket address (protocol/network address/port) is normally permitted
```

Is there a way to prevent that from happening? I guess also, that this error appear only on Windows machines.

**Comment by Neverhorst** [comment]
Has not been observed for years now... closed.
