### ISSUE TITLE
Completely switch qudi to use PyQt5

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#117]
Migration: trac#332.

Now that pyqtgraph 0.10.0 supports Qt5, we can make it the default/only supported version.

**Comment by Neverhorst** [comment]
If I open confocalGUI i get:
`QWindowsWindow::setGeometry: Unable to set geometry 1348x1402+8+31 on QWidgetWindow/'MainWindowWindow'. Resulting geometry:  1348x1053+8+31 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 802x953, maximum size: 16777215x16777215).`

**Comment by latchr** [comment]
This seems to be completed in the qt5-migration branch.
