### ISSUE TITLE
FastComTec HW module "configure" method is not working properly together with logic.

### ISSUE THREAD

**Issue by Neverhorst** [Ulm-IQO/qudi#120]
When changing e.g. fast_counter_binwidth in the pulsed measurement GUI, this value will not be set in hardware. This is only the case with FastComTec hardware so it's most probably an issue with the hardware module itself. I suspect either faulty calculation of the bitshift value or an issue with non-exact float values coming from the GUI (must round to the nearest valid value). Unfortunately I can't test it due to missing said hardware.

**Comment by jochen-scheuer** [comment]
Fixed and tested
