### ISSUE TITLE
Remove SSR additions from pulsed

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#127]
The SSR additions to pulsed violate the general design of Qudi, especially the premise that modules at the logic and GUI level work with ALL the hardware modules that fulfill the specified interface.

Relevant commits:
1dba62767ceee854669145814af4107a1ac6c06f
3742a37f8b58e69789031c167e2830b98f14c044

**Comment by Neverhorst** [comment]
All gone.
