### ISSUE TITLE
Finish reference implementation of new fit selection fitsettings tool.

### ISSUE THREAD

**Issue by latchr** [Ulm-IQO/qudi#141]
The overhauled fitsettings tool offers a full selection of the available fits in fitlogic.  ODMR was the most "established" implementation of fitting, and it is being changed to implement the new fit selection.  This will serve as a reference implementation that can then be adapted to other experiment logics.

**Comment by drogenlied** [comment]
Fully functional since 2320fa864115fe4508db3d3dda8349fd57085d34.
