### ISSUE TITLE
Confocal images have badly formatted coordinate axes

### ISSUE THREAD

**Issue by Neverhorst** [Ulm-IQO/qudi#145]
Probably after changing confocal to only use SI units the saved images have badly formatted numbers written on the axes. (like 0.00001m)
It would be better if either a unit prefix is used for saving (like "nm") or scientific notation would be used on the axes (like 10.00 x 10^-6). Either way the axes need to be scaled to a more convenient format.

**Comment by kay-jahnke** [comment]
Fixed on Master.

The \mu is an upright mathematical symbol, which is technically correct but looks a bit weird. I did not find any way to fix this.

Anyhow, I declare this bug fixed, because now the pictures are acceptable again.
