### ISSUE TITLE
Does the analyze_lifetime method in trace_analysis_logic need exponential fit *without* offset?

### ISSUE THREAD

**Issue by latchr** [Ulm-IQO/qudi#147]
Currently in lines 412 and 428 of trace_analysis_logic there is a call to make_exponentialdecay_fit as part of the analyze_lifetime method.  Is it important that this fit is *without* any constant offset?

**Comment by Geegee** [comment]
Yes we need the model to be without adding a constant offset,
but we don't need this specific model. Just adjusted it to 
use the add_params feature.
