### ISSUE TITLE
Hardware modules get deactivated first when closing qudi

### ISSUE THREAD

**Issue by Neverhorst** [Ulm-IQO/qudi#155]
Strange issue since in the manager it looks as if the hierarchy of the modules is right (GUI first, logic second, hardware last). Still the hardware modules get deactivated early.

**Comment by drogenlied** [comment]
I suspect this was introduced when switching a lot of for loops in manager to use items().
Closing Qudi should be fixed, other operations still need fixes in the form of explicit reverse dependency resolution, not just reversing the starting order.

**Comment by drogenlied** [comment]
I hope module unloading is fixed in master and reloading is fixed in qt5-migration.
