### ISSUE TITLE
can not scroll the spinbox for the colorbar in confocal in qt5-migration branch

### ISSUE THREAD

**Issue by Neverhorst** [Ulm-IQO/qudi#166]
Using the mouse wheel to change the range of the colorbar results in following error:

Traceback (most recent call last):
  File "/home/neverhorst/Software/qudi/qtwidgets/pyqtgraphmod/SpinBox.py", line 406, in stepBy
    exp = abs(val * fudge).log10().quantize(1, ROUND_FLOOR)
NameError: name 'ROUND_FLOOR' is not defined

**Comment by latchr** [comment]
Confirmed, this happens for me also (on a quite different system with potentially different package versions).

**Comment by latchr** [comment]
Fixed by importing ROUND_FLOOR from decimal.
