### ISSUE TITLE
Error when changing fit type in the new fit settings dialog

### ISSUE THREAD

**Issue by latchr** [Ulm-IQO/qudi#169]
When trying to change the function type of a fit in the new fit settings dialog I get the following error:

AttributeError: 'QTabWidget' object has no attribute 'remove'

It seems that the problem occurs when the new fit method has a different set of parameters, and the GUI can't properly repopulate the fit settings tab for that fit.

STEPS TO REPRODUCE
1. Open fit settings and make a new fit (eg called "testing").  Choose fit type Lorentzian
2. Click "OK" and test that fit.
3. Re-open fit settings and adjust the fit type to LorentzianDouble

**Comment by drogenlied** [comment]
Fixed with 0c36175b5ee0f46b168dd2ffee41ee6b3b2c6ea8.
