### ISSUE TITLE
AttributeError when doing optimize after changing optimizer settings

### ISSUE THREAD

**Issue by Neverhorst** [Ulm-IQO/qudi#170]
After you change some values in the optimizer settings OptimizerLogic.use_custom_params is NoneType. This is causing the following error upon doing an optimization:

Traceback (most recent call last):
  File "C:\Software\qudi\logic\optimizer_logic.py", line 489, in do_z_optimization
    if any(self.use_custom_params.values()):
AttributeError: 'NoneType' object has no attribute 'values'

**Comment by drogenlied** [comment]
fixed
