### ISSUE TITLE
POI manager delete last position unfunctional

### ISSUE THREAD

**Issue by cyz75** [Ulm-IQO/qudi#200]
The button 'delete last position' gives an error. 
This function is somehow crucial for working with the POI manager because otherwise one wrong fit in the optimizer leads to loss of all positions.
AttributeError: 'NoneType' object has no attribute 'get_key'
Traceback (most recent call last):

  File "C:\HYPERDIAMOND\Software\qudi\gui\poimanager\poimangui.py", line 650, in goto_poi
    self._poi_manager_logic.go_to_poi(poikey=self._poi_manager_logic.active_poi.get_key())

Delete last position is now a function of the class PoI but I wasn´t able to use it correctly i.e. to delete the last position shift of all POIs

    def delete_last_position(self):  # TODO:Rename to delete_last_position
        """ Delete the last position in the history.

        @return float[4]: the position just deleted.
        """

        if len(self._position_time_trace) > 0:
            return self._position_time_trace.pop()
        else:
            return [-1., -1., -1., -1.]

**Comment by Neverhorst** [comment]
#273 fixed it
