### ISSUE TITLE
Numerical error in scanner voltage range

### ISSUE THREAD

**Issue by AndreaFilipovski** [Ulm-IQO/qudi#202]
When changing the config for confocal we needed 0 to 6.5V as scan range, confocal did not work, giving the error 6.500001 was outside voltage range when after scanning first line. Changing the allowed max voltage value in config to 6.51V resulted in working confocal scanner, leading me to believe that a numerical error in calculating the voltage for my scan range occurred (the used scan range was 5x5x5 mum). 
For config used see default_setup_atto_Niv3.cfg.

**Comment by drogenlied** [comment]
Floating point numbers cannot represent every value exactly and operations on them are not transitive (see http://floating-point-gui.de/, http://floating-point-gui.de/basic/ and other pages on that site).

Complaints about this floating point behaviour can be directed at the IEEE, which is responsible for the corresponding standard: https://en.wikipedia.org/wiki/IEEE_754-2008

If you absolutely need exact values, you need to reimplement most or all of confocal with arbitrary precision arithmetic (like with https://docs.python.org/3/library/decimal.html) at a huge performance cost.
