### ISSUE TITLE
AWG7122 hardware file Interleave mode

### ISSUE THREAD

**Issue by jochen-scheuer** [Ulm-IQO/qudi#216]
When loading PulsedMeasurement and Interleave is off, then Interleave is turned on Sampling Rate is restricted.
The reason for that: there is in the get_constraints method  in the hardware file something like if self.interleave

**Comment by Neverhorst** [comment]
Looking at the code of the `AWG7k` class, the issue has been resolved already. In `get_constraints` the return values are dependent on the state of interleave.
