### ISSUE TITLE
Asset name missing in call to _direct_write_sequence

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#239]
## *What* is affected by this bug?

For an all-digital pulser device, `direct_write_sequence` cannot be implemented due to asset names missing from the `name` element in the `sequence_params` dictionary.

## *When* does this occur?

Every time a sequence is generated for a device with only digital channels.

## *Where* on the platform does it happen?

See sequence_generator_logic.py, line 944 to 994.

## *How* do we replicate the issue?

- get a dtg3554
- check out dtg3554 branch
- in pulsed gui, create an ensemble
- create a sequence from the ensemble
- try to upload sequence

## Expected behavior (i.e. solution)

The `name` element in the `sequence_params` dictionary should cintain the correct asset names.

**Comment by Neverhorst** [comment]
Fixed by PR #384
