### ISSUE TITLE
Loading Block  does not load name

### ISSUE THREAD

**Issue by jochen-scheuer** [Ulm-IQO/qudi#245]
## *What* is affected by this bug?

Working with the GUI in pulsed measurement

## *When* does this occur?

Everytime loading an pulse block or ensemble

## *Where* on the platform does it happen?

No exception

## *How* do we replicate the issue?

Load a saved pulse block

## Expected behavior (i.e. solution)

Name should be loaded

##Other Comments

**Comment by Neverhorst** [comment]
Fixed with commit b3e202e3e3f2d363904913e942859aed8952fa8f
