### ISSUE TITLE
When generating Pulse Block ensemble, list below is reordered

### ISSUE THREAD

**Issue by jochen-scheuer** [Ulm-IQO/qudi#246]
## *What* is affected by this bug?

GUI

## *When* does this occur?

Always

## *Where* on the platform does it happen?

Everywhere

## *How* do we replicate the issue?

Generate ensemble

## Expected behavior (i.e. solution)

Show generated Pulse Block ensemble 

##Other Comments

**Comment by Neverhorst** [comment]
Fixed with commit b3e202e3e3f2d363904913e942859aed8952fa8f
