### ISSUE TITLE
Index for Pulse to be displayed in Pulse extraction can not be higher than number of pulses

### ISSUE THREAD

**Issue by jochen-scheuer** [Ulm-IQO/qudi#247]
## *What* is affected by this bug?

When you start a measurement with 200 pulses and look at pulse 180 and in the next measurement you only have 100 pulses measurement does not start

## *When* does this occur?

see above

## *Where* on the platform does it happen?

Windows

## *How* do we replicate the issue?

see above

## Expected behavior (i.e. solution)

Reset to sum when starting experiment

##Other Comments

**Comment by Neverhorst** [comment]
Fixed with commit b3e202e3e3f2d363904913e942859aed8952fa8f
