### ISSUE TITLE
Convenience in pulsed measurement gui

### ISSUE THREAD

**Issue by Geegee** [Ulm-IQO/qudi#262]
## Where could the software be improved?
In the predefined methods tab of the pulsedmeasurement gui 
many methods share common arguments (e.g. laser delay, microwave freq. etc).
Therefore it would be desirable to reduce the redundant operations when adjusting
measurement sequences while keeping the same flexibility the current model offers.

**Comment by Neverhorst** [comment]
Fixed with pull request #269
