### ISSUE TITLE
Counter-oversample bug

### ISSUE THREAD

**Issue by simonschmitt2** [Ulm-IQO/qudi#287]
## *What* is affected by this bug?

Functionality of the slow counter on master branch (all dummy modules). Problem is probably in counter_logic. More specific when changing the oversampling to >1 the following problems arise:

* after stopping the count frequency and the oversampling cannot be adjusted in the GUI
* when trying to record counts the counter throws an error:

![grafik](https://user-images.githubusercontent.com/18697822/31895114-9963dba2-b810-11e7-96e2-3678003fcd30.png)

![grafik](https://user-images.githubusercontent.com/18697822/31895393-55814b12-b811-11e7-8c95-24a63a852e88.png)

![grafik](https://user-images.githubusercontent.com/18697822/31895236-f1372b86-b810-11e7-8d0f-e67d834bd8ae.png)

(deleting ', 0' in the last line seems to help)
* this error prevents that the counter works after a restart (even for oversampling=1)
* the time-axis (x-axis) is not correct anymore
* the pdf and png of the recoreded data look very strange

![grafik](https://user-images.githubusercontent.com/18697822/31895753-4e746722-b812-11e7-8b4d-307554c300ef.png)

## *When* does this occur?

Setting oversampling > 1 and trying to record data. Probably the lines of code from above have to be changed

## *How* do we replicate the issue?

1. Load counter GUI
2. Change oversampling
3. Start counter
4. Record data

## Expected behavior (i.e. solution)

There should be no error message and the saved data should be the measured one

##Other Comments

**Comment by LukePiewalker** [comment]
Since the slow counter module is now deprecated, I think this Issue can be closed right @Neverhorst?

**Comment by Neverhorst** [comment]
That's right @LukePiewalker. Old `CounterLogic` has been completely replaced by `TimeSeriesReaderLogic`.
