### ISSUE TITLE
Global parameters in predefined methods tab is not saved when closing pulsedmaingui

### ISSUE THREAD

**Issue by SimonSchmitt88** [Ulm-IQO/qudi#299]
## *What* is affected by this bug?

When there are changes in the global parameters done they are not saved and when qudi is restarted (the gui is reloaded) the hardcoded values are taken. This is unconvenient and leads to mistakes... Especially after a new sequence should be implemented and during testing multiple reloads might be neccessary.

## *When* does this occur?

After every new start of qudi/ reload of the pulsedmaingui

## Expected behavior (i.e. solution)

When the pulsedmaingui is closed the global parameters should be saved and taken when the gui is reloaded.

##Other Comments

**Comment by Neverhorst** [comment]
Fixed by PR #384
