### ISSUE TITLE
Every new extraction or analysis parameter has to be added to the GUI by hand

### ISSUE THREAD

**Issue by SimonSchmitt88** [Ulm-IQO/qudi#300]
## *What* is affected by this bug?

If there is a new extraction (analysis) method and this method needs parameters which are currently not present in the GUI one has to add a new input box (or similar). Over time this could lead to space problems and limits the overview. 

## Expected behavior (i.e. solution)

So it would be nice if the gui displays only the parameters for the currently chosen extraction (analysis) method (similar of how it is done in the predefined methods or for the magnet)

##Other Comments

**Comment by Neverhorst** [comment]
Fixed by PR #384
