### ISSUE TITLE
ODMR runtime and sweep_power are not updated in GUI when changed in logic

### ISSUE THREAD

**Issue by SimonSchmitt88** [Ulm-IQO/qudi#303]
## *What* is affected by this bug?

When changing the odmr runtime using 'odmrlogic.set_runtime(xx) ', the run time is changed, but the GUI is not updated. Same is true for the sweep_power when using: odmrlogic.set_sweep_parameters(freq_start,freq_end,freq_step,sweep_power)
(all other parameters are updated)

## *When* does this occur?

Always

## Expected behavior (i.e. solution)

##Other Comments

**Comment by Neverhorst** [comment]
That is no wonder.
Use the "setter-method" instead. That's what it was made for.
See: "set_runtime ()"

**Comment by Neverhorst** [comment]
#305 fixed that issue.
