### ISSUE TITLE
Windows not showing up after firing up the GUI

### ISSUE THREAD

**Issue by hellbourne** [Ulm-IQO/qudi#327]

**Comment by a-stark** [comment]
I suppose that the installation instructions were not followed correctly. On Windows 10, you need to install Anaconda for **all users** (which requires admin privileges). Could you repeat the anaconda installation and then also the installation of Qudi described [in the docs](privileges)?

**Comment by hellbourne** [comment]
Solved by pulling the newest version.

**Comment by a-stark** [comment]
awesome.
