### ISSUE TITLE
Problems with the fit accuracy of period

### ISSUE THREAD

**Issue by SimonSchmitt88** [Ulm-IQO/qudi#354]
## *What* is affected by this bug?

When doing any sine-fit the fit 'error' of the period sometimes seems to be too large. (Not sure if this true  for other fit-function as well)

## *When* does this occur?

In the example data below, it is not possible to obtain the period from the fitparameters due to the large error, which seems although the data is noisy and not even a full period is fitted, too large. Also the relative error in the frequency estimate is much lower, what seems surprising.

![grafik](https://user-images.githubusercontent.com/18697822/38086148-91888b80-3353-11e8-8f4c-faf11590ce99.png)

![grafik](https://user-images.githubusercontent.com/18697822/38086138-8a78c6e8-3353-11e8-965b-45e8c6faba34.png)

## Expected behavior (i.e. solution)

The error of the period should be smaller and the relative errors of period and frequency should be the same.

**Comment by SimonSchmitt88** [comment]
Thanks! I think this is exactly the problem and frequency_error/(frequency**2) should be the correct equation. I will test your branch as soon as possible.

Do you mean with contrast just twice the amplitude or something more specific?

**Comment by Neverhorst** [comment]
Fixed by PR #370
