### ISSUE TITLE
POIManager: Measure distance between POIs

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#53]
Migration: trac#20.

Make a tool in POImanager that can measure distances.

**Comment by kay-jahnke** [comment]
I will track the distance to the mouse when moving over the field of view on the poimanager.
How exactly do you need the distance?
(Delta x, Delta y) or the distance along a line?

**Comment by kay-jahnke** [comment]
Implemented both measures on the master branch. (see commit  4bae5fe )
Please test, before we close this issue.

**Comment by kay-jahnke** [comment]
should be fine now.
