### ISSUE TITLE
Confocal scan: moving the corss hair in the XY-scan does not update the X position in the depth scan (XZ)

### ISSUE THREAD

**Issue by miffi-svg** [Ulm-IQO/qudi#613]
## *What* is affected by this bug?
Changing the position of the cross hair in the XY-scan of the confocal scan module does not change/update the position of the cross hair position in the depth scan, meaning the X-position in the XZ-scan or the Y-position in the YZ-scan. The other way around it works fine. So, if the cross hair in the depth scan is moved, the cross hair jumps to the current location, which might be harmful for the scanner (piezo controlled) in the long run.

## *Where* on the platform does it happen?

Confocal scan module of the current version of qudi (Qudi v0.10 (Pulsed 3.0))

## *How* do we replicate the issue?

1. Open the confocal scan module
2. Move the cross hair position in the XY-scan
3. Move the cross hair in the XZ-scan (or YZ-scan) -> the cross hair in the XY-scan will jump to the current X- (or Y-) value of the depth scan  

## Expected behavior (i.e. solution)
Moving the cross hair in the XY-scan should update the position in the depth scan (XZ- and YZ-scan), how it works the other way around.

**Comment by NicolasStaudenmaier** [comment]
Thanks for opening this issue. I have encountered the same bug, which is also quite annoying if you change the crosshair in the depth scan and you loose the x- (or y-) position. When the pull request is merged into master the problem will be solved.
