### ISSUE TITLE
In predefinded sequence: make an option which lets you chose if blocks are written to gui or not

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#66]
Migration: trac#71.

Now the GUI editor is always updated with the created sequence. But no choice can be made to NOT load into editor.

**Comment by Neverhorst** [comment]
Is that really desirable after all? People are always complaining that they want to scroll through the sequence and check if everything is as expected. This is why the predefined sequences are now automatically loaded into the editor. You can always change to a previously generated block/ensemble/sequence by selecting it and pressing load in the editor side bar.

**Comment by Neverhorst** [comment]
I think we can close this issue due to inactivity. No one responded here (also not before on trac) so I think the reporter lost interest in the issue.
