### ISSUE TITLE
Implementation of Hardware File for Keysight AWG 

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#68]
Migration: trac#78.

We have a Keysight AWG, make a pulser hardware file for it.

**Comment by a-stark** [comment]
An implementation attempt is performed in the branch [awg_m8195_implementation](https://github.com/Ulm-IQO/qudi/tree/awg_m8195_implementation). It needs to be adapted to the new pulser interface.

**Comment by Neverhorst** [comment]
**poke**
