### ISSUE TITLE
Issue with starting the new qudi core

### ISSUE THREAD

**Issue by rbs220896** [Ulm-IQO/qudi#709]
I have a error when i have tried to start the new qudi core, where the following errors are shown. I have tried to put the right configuration file but the error still remains
<img width="960" alt="Error1" src="https://user-images.githubusercontent.com/94909455/236692780-4e20b31f-eaa2-4b41-8e01-710b9b87ccfb.png">

<img width="960" alt="Error2" src="https://user-images.githubusercontent.com/94909455/236692831-9b78f2c0-2fc7-4006-940e-ee6e1cd905f0.png">

<img width="960" alt="Error3" src="https://user-images.githubusercontent.com/94909455/236692836-37abf0b1-c23b-4ba5-82c4-3d3b916cb15b.png">

**Comment by qku** [comment]
Hi @rbs220896 , the place to ask questions about the new core is the discussion page: https://github.com/Ulm-IQO/qudi-core/discussions
