### ISSUE TITLE
Debug sampling of Pulse_Sequence objects. 

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#85]
Migration: trac#199.

After merging of the branches the Pulse_Sequence sampling methods are outdated. Step through the process and make it work properly. Take the sample_pulse_block_ensemble method as example. The conventions used there (channel identification etc.) are a good starting point.
This is mainly concerning sequence_generator_logic.py and samples_write_methods.py.

Works with current version after commit 80a1811cafa79e865942577f477857af4258e51a but is still written in a not very good way.

**Comment by Neverhorst** [comment]
Works now in a stable and good way (v0.7). If there are more issues related to the sampling of pulse sequences, one needs to open a more specific issue for that.

The convention is currently as follows:
If the rotating frame should be preserved across PulseBlockEnsembles within a sequence, the created waveform filenames are composed of "sequencename_3digitnumberofstep_channelspecifier.fileformat" (i.e. "testseq_001_ch1.wfm")
If rotating frame is only maintained within the PulseBlockEnsembles (or not at all) the waveform filenames are called the same as when you sample the ensemble alone. (i.e. "ensemblename_ch1.wfm").
All created waveforms are uploaded to the device as soon as they are created and the sequence file itself is created and uploaded last.
