### ISSUE TITLE
Rethink the Pulse_Sequence class and adjust accordingly

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#86]
Migration: trac#200.

The Pulse_Sequence objects are currently much more complicated than they need to be. Think of what's the basic infomation that needs to be in this object and create corresponding attributes for that. (Instead of a params dictionary) Therefore we need to figure out what's the common parameter set for all AWGs (and DTG) to describe a sequence.

**Comment by Neverhorst** [comment]
Fixed by PR #384
