### ISSUE TITLE
Implement a proper return value for on and off method of microwave interface

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#91]
Migration: trac#211.

Currently the microwave interface has the methods on() and off().
The hardware files, which are using this interface have to output a proper return value, to check whether the device is really on or off. I.e. after turning on the device, one has to ask the state of the device and return a zero, if everything is fine, otherwise a -1 has to be returned with an error message before that.
That will ensure a proper reaction of the Logic on the state of the microwave device.

**Comment by Neverhorst** [comment]
Works after commit 5d021a8f390c26752e0d574696eb106237ddc213 except for Gigatronics MW source since no query command is provided to ask for the output state of the device.
