### ISSUE TITLE
separate ensemble and sequence generation in predefined methods the

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#93]
Migration: trac#216.

The predefined methods have a generation method and an upload method, which is connected to the generation and upload of only pulse block ensembles! In order to use pulse sequence generation, one needs either a separate file, where the sequence creation methods are present, or the functions, which builds dynamically the creation methods in the GUI, have to distinguish between ensemble creation and sequence creation (to my mind, that can only be done by names, i.e. attaching a suffix like _seq to the generation method.)

**Comment by drogenlied** [comment]
I think this is fixed or will be fixed with #384.

**Comment by Neverhorst** [comment]
Fixed by PR #384
